spring:
  application:
    name: 'apiProduct'

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://db-product.c1y0qqm4gcce.us-east-1.rds.amazonaws.com:3306/dbproduct?useSSL=false
    username: admin
    password: ${DB_PASSWORD} #Environment variable
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000


  jpa:
    show-sql: true
    generate-ddl: true #to create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  packages-to-scan: com.apiproduct.controller

caching:
  spring:
    productListTTL: 120000
