spring:
  application:
    name: 'apiProduct'

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD} #Environment variable
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000


  jpa:
    show-sql: true
    generate-ddl: true #to create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        opaque-token.introspection-uri: http://localhost:8081/oauth2/introspect
        # ENVIRONMENT TOKEN_CLI_ID=example;TOKEN_CLI_SECRET=example;DB_PASSWORD=example
        opaque-token.client-id: ${TOKEN_CLI_ID}
        opaque-token.client-secret: ${TOKEN_CLI_SECRET}
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  packages-to-scan: com.apiproduct.controller

caching:
  spring:
    productListTTL: 120000
